apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-frontend
  template:
    metadata:
      labels:
        app: crud-frontend
    spec:
      containers:
        - name: crud-frontend
          image: your-dockerhub-username/crud-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://crud-api:80"
---
apiVersion: v1
kind: Service
metadata:
  name: crud-frontend
spec:
  selector:
    app: crud-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
