apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-api
  template:
    metadata:
      labels:
        app: crud-api
    spec:
      containers:
        - name: crud-api
          image: your-dockerhub-username/crud-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: crud-api
spec:
  selector:
    app: crud-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
